language: node_js
node_js:
  - "0.11"
before_script:
    # install dependencies
    - npm install -g gulp
    - sleep 2
script:
    # We want to gate on passing tests and a successful build
    - gulp